### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by c0derm4n** [ShannonAI/service-streamer#69]
File "/media/huaxin/tcl2/nlp/dumingyu_project/bertlk/web_service/advanced_deploy_api.py", line 76, in <module>
    streamer = Streamer(model.predict, batch_size=8, max_latency=0.1, worker_num=1)
  File "/media/huaxin/tcl2/nlp/dumingyu_project/bertlk/web_service/service_streamer.py", line 296, in __init__
    self._setup_gpu_worker()
  File "/media/huaxin/tcl2/nlp/dumingyu_project/bertlk/web_service/service_streamer.py", line 311, in _setup_gpu_worker
    p.start()
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/media/huaxin/tcl2/nlp/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

**Comment by yjiangling** [comment]
@Meteorix @pku-wuwei Same Error, please give some help, thanks a lot!

Traceback (most recent call last):
  File "asr_api.py", line 92, in <module>
    streamer=Streamer(model.predict,batch_size=4,max_latency=0.01)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/service_streamer/service_streamer.py", line 267, in __init__
    self._setup_gpu_worker()
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/service_streamer/service_streamer.py", line 280, in _setup_gpu_worker
    p.start()
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/media/huaxin/tcl1/asr/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle LockType objects
